version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  django:
    container_name: django
    build: ./
    volumes:
      - ./src:/src:rw
      - ./.env:/src/core/.env
    depends_on:
      - postgres
    ports:
      - 8000:8000
