# Generated by Django 3.2.8 on 2021-10-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='restaurant_name', max_length=128, verbose_name='restaurant_name')),
                ('state', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='closed', help_text='state', max_length=10, verbose_name='state')),
                ('address', models.CharField(help_text='restaurant_address', max_length=128, verbose_name='restaurant_address')),
                ('rating', models.IntegerField(default=0, help_text='rating', verbose_name='rating')),
                ('phone', models.CharField(help_text='phone', max_length=128, verbose_name='phone')),
                ('cuisine', models.CharField(help_text='cuisine', max_length=128, verbose_name='cuisine')),
                ('is_active', models.BooleanField(default=True, help_text='is_active', verbose_name='is_active')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='created', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='modified', verbose_name='modified')),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
                'db_table': 'restaurant.restaurants',
            },
        ),
    ]
