# Generated by Django 3.2.8 on 2021-10-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='rating', verbose_name='rating'),
        ),
    ]
